// ============================================================================
// OPENING CRAWL TEXT - PROPER LINE BY LINE
// ============================================================================

static const char *OPENING_CRAWL_LINES[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "In the not so distant future in a galaxy",
    "not so far away",
    "",
    "",
    "The Kepler-442 Asteroid Field, once a",
    "treasure trove of minerals, now lies",
    "in ruin.",
    "Asteroids fracture, comets drift", 
    "factions clash.",
    "",
    "Red warships hunt without mercy.",
    "Blue patrols guard with fragile", 
    "honor.",
    "Green drones strip-mine with ruthless ",
    "speed.",
    "And now... the PURPLE SENTINELS",
    "arrive—enigmatic guardians with",
    "unknown intent.",
    "",
    "You fly the DESTINY--",
    "an ancient warship of unknown origin,",
    "reborn as a mining vessel,",
    "armed with rapid-fire cannons,",
    "advanced thrusters, drone missles,",
    "and omnidirectional fire.",
    "",
    "It is fragile, yet fierce.",
    "It carries no banner, no allegiance,",
    "only the will to survive.",
    "",
    "But survival is not enough.",
    "Beyond the factions loom colossal",
    "threats:",
    "MEGA BOSS SHIPS, engines of",
    "annihilation,",
    "whose presence darkens the field",
    "itself.",
    "",
    "And deeper still, from the void,",
    "alien forces gather—",
    "a tide that consumes all in its path.",
    "",
    "Your mission: endure the chaos,",
    "outwit rival factions,",
    "and face the horrors that await.",
    "",
    "The asteroid field is no longer a mine.",
    "It is a crucible of war.",
    "",
    "Survive. Score. Ascend.",
    "",
    "",
};

#define NUM_CRAWL_LINES (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES[0]))

// ============================================================================
// VICTORY SCROLL TEXT - FINALE WHEN WAVE 30 IS BEATEN
// ============================================================================

static const char *VICTORY_SCROLL_LINES[] = {
    "",
    "",
    "",
    "THE KEPLER-442 INCIDENT:",
    "CONCLUDED",
    "",
    "The asteroids... they", 
    "were never truly chaotic.",
    "",
    "As you clear the final",
    "waves from the field,",
    "the truth crystallizes",
    "in the wreckage of a",
    "thousand ships.",
    "This was not a",
    "mining operation.",
    "It was a crucible. A test.",
    "",
    "The three factions sent ",
    "their finest.",
    "The Red Warships of the",
    "Galactic Defense Collective.",
    "The peaceful patrols of the",
    "Independent Sector Alliance.",
    "The corporate drones of ",
    "the Asteroid Mining Collective.",
    "",
    "You destroyed them all.",
    "",
    "The Purple Sentinels...",
    "they were watching.",
    "Observing. Calculating ...",
    "Waiting.",
    "When the final Juggernaut fell",
    "to your fire,",
    "they simply... departed.",
    "",
    "As if satisfied.",
    "",
    "The DESTINY's ancient systems",
    "hum with purpose.",
    "Weapons that should not exist.",
    "Shields that defy physics.",
    "A ship of unknown origin,",
    "reborn as a mining vessel,",
    "now standing victorious",
    "in a field of ash and silence.",
    "",
    "What are you, truly?",
    "What was the DESTINY, before?",
    "",
    "The void offers no answers.",
    "Only echoes.",
    "",
    "You have restored order",
    "to Kepler-442.",
    "The factions will reconsider",
    "their ambitions.",
    "The Sentinels have completed",
    "their observations.",
    "The Golden Juggernauts lie dormant",
    "in the dark.",
    "",
    "But something remains.",
    "",
    "At the edge of the asteroid field,",
    "beyond the reach of conventional",
    "sensors, something ancient stirs.",
    "",
    "The DESTINY's original designers ",
    "are watching.",
    "They are pleased with what you ",
    "have become.",
    "",
    "They are waiting.",
    "",
    "They are preparing.",
    "",
    "They will be ready.",
    "",
    "",
    "",
};

#define NUM_VICTORY_LINES (sizeof(VICTORY_SCROLL_LINES) / sizeof(VICTORY_SCROLL_LINES[0]))

// ============================================================================
