// ============================================================================
// OPENING CRAWL TEXT - PROPER LINE BY LINE
// ============================================================================

static const char *OPENING_CRAWL_LINES[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "In the not so distant future in a galaxy",
    "not so far away",
    "",
    "",
    "The Kepler-442 Asteroid Field, once a",
    "treasure trove of minerals, now lies",
    "in ruin.",
    "Asteroids fracture, comets drift", 
    "factions clash.",
    "",
    "Red warships hunt without mercy.",
    "Blue patrols guard with fragile", 
    "honor.",
    "Green drones strip-mine with ruthless ",
    "speed.",
    "And now... the PURPLE SENTINELS",
    "arrive—enigmatic guardians with",
    "unknown intent.",
    "",
    "You fly the DESTINY--",
    "an ancient warship of unknown origin,",
    "reborn as a mining vessel,",
    "armed with rapid-fire cannons,",
    "advanced thrusters, drone missles,",
    "and omnidirectional fire.",
    "",
    "It is fragile, yet fierce.",
    "It carries no banner, no allegiance,",
    "only the will to survive.",
    "",
    "But survival is not enough.",
    "Beyond the factions loom colossal",
    "threats:",
    "MEGA BOSS SHIPS, engines of",
    "annihilation,",
    "whose presence darkens the field",
    "itself.",
    "",
    "And deeper still, from the void,",
    "alien forces gather—",
    "a tide that consumes all in its path.",
    "",
    "Your mission: endure the chaos,",
    "outwit rival factions,",
    "and face the horrors that await.",
    "",
    "The asteroid field is no longer a mine.",
    "It is a crucible of war.",
    "",
    "Survive. Score. Ascend.",
    "",
    "",
};

#define NUM_CRAWL_LINES (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES[0]))

static const char *OPENING_CRAWL_ES[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "En un futuro no tan distante, en una galaxia",
    "no tan lejana",
    "",
    "",
    "El Campo de Asteroides Kepler-442, antes un",
    "tesoro de minerales, ahora yace",
    "en ruinas.",
    "Los asteroides se fracturan, los cometas vagan,",
    "las facciones chocan.",
    "",
    "Los acorazados rojos cazan sin piedad.",
    "Las patrullas azules vigilan con frágil",
    "honor.",
    "Los drones verdes extraen sin descanso,",
    "con velocidad implacable.",
    "Y ahora... los CENTINELAS PÚRPURA",
    "llegan—guardianes enigmáticos con",
    "intenciones desconocidas.",
    "",
    "Pilotas la DESTINY--",
    "una antigua nave de guerra de origen desconocido,",
    "renacida como nave minera,",
    "armada con cañones de disparo rápido,",
    "propulsores avanzados, misiles dron,",
    "y fuego omnidireccional.",
    "",
    "Es frágil, pero feroz.",
    "No porta bandera ni lealtad,",
    "solo la voluntad de sobrevivir.",
    "",
    "Pero sobrevivir no basta.",
    "Más allá de las facciones se alzan",
    "amenazas colosales:",
    "NAVES MEGA JEFE, motores de",
    "aniquilación,",
    "cuya presencia oscurece el campo",
    "mismo.",
    "",
    "Y más profundo aún, desde el vacío,",
    "fuerzas alienígenas se reúnen—",
    "una marea que consume todo a su paso.",
    "",
    "Tu misión: soportar el caos,",
    "burlar a las facciones rivales,",
    "y enfrentar los horrores que te esperan.",
    "",
    "El campo de asteroides ya no es una mina.",
    "Es un crisol de guerra.",
    "",
    "Sobrevive. Puntúa. Asciende.",
    "",
    "",
};

#define NUM_CRAWL_LINES_ES (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES_ES[0]))

static const char *OPENING_CRAWL_FR[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "Dans un futur pas si lointain, dans une galaxie",
    "pas si éloignée",
    "",
    "",
    "Le Champ d’Astéroïdes Kepler-442, autrefois",
    "un trésor de minéraux, gît désormais",
    "en ruines.",
    "Les astéroïdes se fracturent, les comètes dérivent,",
    "les factions s’affrontent.",
    "",
    "Les vaisseaux de guerre rouges chassent sans pitié.",
    "Les patrouilles bleues veillent avec un",
    "honneur fragile.",
    "Les drones verts exploitent sans relâche,",
    "avec une vitesse impitoyable.",
    "Et maintenant… les SENTINELLES VIOLETTES",
    "arrivent — des gardiens énigmatiques aux",
    "intentions inconnues.",
    "",
    "Vous pilotez le DESTINY--",
    "un ancien vaisseau de guerre d’origine inconnue,",
    "renaît comme navire minier,",
    "armé de canons à tir rapide,",
    "de propulseurs avancés, de missiles‑drones,",
    "et d’un tir omnidirectionnel.",
    "",
    "Il est fragile, mais féroce.",
    "Il ne porte ni bannière ni allégeance,",
    "seulement la volonté de survivre.",
    "",
    "Mais survivre ne suffit pas.",
    "Au‑delà des factions se dressent des",
    "menaces colossales :",
    "des MÉGA VAISSEAUX‑BOSSES, moteurs",
    "d’annihilation,",
    "dont la présence assombrit le champ",
    "lui‑même.",
    "",
    "Et plus loin encore, depuis le vide,",
    "des forces extraterrestres se rassemblent —",
    "une marée qui dévore tout sur son passage.",
    "",
    "Votre mission : endurer le chaos,",
    "déjouer les factions rivales,",
    "et affronter les horreurs qui vous attendent.",
    "",
    "Le champ d’astéroïdes n’est plus une mine.",
    "C’est un creuset de guerre.",
    "",
    "Survivez. Marquez. Élevez‑vous.",
    "",
    "",
};

#define NUM_CRAWL_LINES_FR (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES_FR[0]))

static const char *OPENING_CRAWL_RU[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "В недалёком будущем, в галактике",
    "не такой уж далёкой",
    "",
    "",
    "Поле астероидов Кеплер‑442, некогда",
    "кладезь минералов, теперь лежит",
    "в руинах.",
    "Астероиды трескаются, кометы блуждают,",
    "фракции сталкиваются.",
    "",
    "Красные боевые корабли охотятся без пощады.",
    "Синие патрули стережёт хрупкая",
    "честь.",
    "Зелёные дроны выкачивают ресурсы",
    "с беспощадной скоростью.",
    "И теперь… ФИОЛЕТОВЫЕ СЕНТИНЕЛЫ",
    "прибывают — загадочные стражи с",
    "неизвестными намерениями.",
    "",
    "Вы пилотируете DESTINY--",
    "древний боевой корабль неизвестного происхождения,",
    "возрождённый как добывающий корабль,",
    "оснащённый скорострельными пушками,",
    "усовершенствованными двигателями, ракетами‑дронами",
    "и всенаправленным огнём.",
    "",
    "Он хрупок, но свиреп.",
    "Он не несёт ни знамени, ни верности,",
    "только волю выжить.",
    "",
    "Но выживания недостаточно.",
    "За пределами фракций нависают",
    "колоссальные угрозы:",
    "МЕГА‑КОРАБЛИ БОССОВ — машины",
    "уничтожения,",
    "чьё присутствие омрачает само",
    "поле.",
    "",
    "И глубже, из пустоты,",
    "собираются инопланетные силы —",
    "волна, поглощающая всё на своём пути.",
    "",
    "Ваша миссия: выдержать хаос,",
    "перехитрить соперничающие фракции",
    "и встретить ужасы, что ждут впереди.",
    "",
    "Поле астероидов больше не шахта.",
    "Это горнило войны.",
    "",
    "Выживи. Заработай. Вознесись.",
    "",
    "",
};

#define NUM_CRAWL_LINES_RU (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES_RU[0]))

// ============================================================================
// VICTORY SCROLL TEXT - FINALE WHEN WAVE 30 IS BEATEN
// ============================================================================

static const char *VICTORY_SCROLL_LINES[] = {
    "",
    "",
    "",
    "THE KEPLER-442 INCIDENT:",
    "CONCLUDED",
    "",
    "The asteroids... they", 
    "were never truly chaotic.",
    "",
    "As you clear the final",
    "waves from the field,",
    "the truth crystallizes",
    "in the wreckage of a",
    "thousand ships.",
    "This was not a",
    "mining operation.",
    "It was a crucible. A test.",
    "",
    "The three factions sent ",
    "their finest.",
    "The Red Warships of the",
    "Galactic Defense Collective.",
    "The peaceful patrols of the",
    "Independent Sector Alliance.",
    "The corporate drones of ",
    "the Asteroid Mining Collective.",
    "",
    "You destroyed them all.",
    "",
    "The Purple Sentinels...",
    "they were watching.",
    "Observing. Calculating ...",
    "Waiting.",
    "When the final Juggernaut fell",
    "to your fire,",
    "they simply... departed.",
    "",
    "As if satisfied.",
    "",
    "The DESTINY's ancient systems",
    "hum with purpose.",
    "Weapons that should not exist.",
    "Shields that defy physics.",
    "A ship of unknown origin,",
    "reborn as a mining vessel,",
    "now standing victorious",
    "in a field of ash and silence.",
    "",
    "What are you, truly?",
    "What was the DESTINY, before?",
    "",
    "The void offers no answers.",
    "Only echoes.",
    "",
    "You have restored order",
    "to Kepler-442.",
    "The factions will reconsider",
    "their ambitions.",
    "The Sentinels have completed",
    "their observations.",
    "The Golden Juggernauts lie dormant",
    "in the dark.",
    "",
    "But something remains.",
    "",
    "At the edge of the asteroid field,",
    "beyond the reach of conventional",
    "sensors, something ancient stirs.",
    "",
    "The DESTINY's original designers ",
    "are watching.",
    "They are pleased with what you ",
    "have become.",
    "",
    "They are waiting.",
    "",
    "They are preparing.",
    "",
    "They will be ready.",
    "",
    "",
    "",
};

#define NUM_VICTORY_LINES (sizeof(VICTORY_SCROLL_LINES) / sizeof(VICTORY_SCROLL_LINES[0]))

static const char *VICTORY_SCROLL_ES[] = {
    "",
    "",
    "",
    "EL INCIDENTE DE KEPLER‑442:",
    "CONCLUIDO",
    "",
    "Los asteroides… ellos",
    "nunca fueron realmente caóticos.",
    "",
    "Al despejar las últimas",
    "oleadas del campo,",
    "la verdad se cristaliza",
    "entre los restos de",
    "mil naves.",
    "Esto no fue una",
    "operación minera.",
    "Fue un crisol. Una prueba.",
    "",
    "Las tres facciones enviaron",
    "a sus mejores.",
    "Los Acorazados Rojos del",
    "Colectivo de Defensa Galáctica.",
    "Las patrullas pacíficas de la",
    "Alianza del Sector Independiente.",
    "Los drones corporativos del",
    "Colectivo Minero de Asteroides.",
    "",
    "Los destruiste a todos.",
    "",
    "Los Centinelas Púrpura…",
    "estaban observando.",
    "Observando. Calculando…",
    "Esperando.",
    "Cuando el último Juggernaut cayó",
    "ante tu fuego,",
    "simplemente… se marcharon.",
    "",
    "Como si estuvieran satisfechos.",
    "",
    "Los antiguos sistemas del DESTINY",
    "zumban con propósito.",
    "Armas que no deberían existir.",
    "Escudos que desafían la física.",
    "Una nave de origen desconocido,",
    "renacida como nave minera,",
    "ahora en pie victoriosa",
    "en un campo de cenizas y silencio.",
    "",
    "¿Qué eres, en realidad?",
    "¿Qué fue el DESTINY, antes?",
    "",
    "El vacío no ofrece respuestas.",
    "Solo ecos.",
    "",
    "Has restaurado el orden",
    "en Kepler‑442.",
    "Las facciones reconsiderarán",
    "sus ambiciones.",
    "Los Centinelas han completado",
    "sus observaciones.",
    "Los Juggernauts Dorados yacen inactivos",
    "en la oscuridad.",
    "",
    "Pero algo permanece.",
    "",
    "En el borde del campo de asteroides,",
    "más allá del alcance de los",
    "sensores convencionales, algo antiguo despierta.",
    "",
    "Los diseñadores originales del DESTINY",
    "te observan.",
    "Están complacidos con lo que",
    "te has convertido.",
    "",
    "Están esperando.",
    "",
    "Se están preparando.",
    "",
    "Estarán listos.",
    "",
    "",
    "",
};

#define NUM_VICTORY_LINES_ES (sizeof(VICTORY_SCROLL_LINES) / sizeof(VICTORY_SCROLL_LINES_ES[0]))

static const char *VICTORY_SCROLL_FR[] = {
    "",
    "",
    "",
    "L’INCIDENT DE KEPLER‑442 :",
    "CONCLU",
    "",
    "Les astéroïdes… ils",
    "n’ont jamais été vraiment chaotiques.",
    "",
    "Lorsque vous nettoyez les dernières",
    "vagues du champ,",
    "la vérité se cristallise",
    "dans l’épave de",
    "milliers de vaisseaux.",
    "Ce n’était pas une",
    "opération minière.",
    "C’était un creuset. Une épreuve.",
    "",
    "Les trois factions ont envoyé",
    "leurs meilleurs.",
    "Les Vaisseaux Rouges du",
    "Collectif de Défense Galactique.",
    "Les patrouilles pacifiques de",
    "l’Alliance du Secteur Indépendant.",
    "Les drones corporatifs du",
    "Collectif Minier d’Astéroïdes.",
    "",
    "Vous les avez tous détruits.",
    "",
    "Les Sentinelles Violettes…",
    "elles observaient.",
    "Observant. Calculant…",
    "Attendant.",
    "Quand le dernier Juggernaut est tombé",
    "sous votre feu,",
    "elles ont simplement… quitté les lieux.",
    "",
    "Comme satisfaites.",
    "",
    "Les anciens systèmes du DESTINY",
    "vibrent d’un but précis.",
    "Des armes qui ne devraient pas exister.",
    "Des boucliers défiant la physique.",
    "Un vaisseau d’origine inconnue,",
    "renaît comme navire minier,",
    "désormais victorieux",
    "dans un champ de cendres et de silence.",
    "",
    "Qui êtes‑vous vraiment ?",
    "Qu’était le DESTINY, autrefois ?",
    "",
    "Le vide n’offre aucune réponse.",
    "Seulement des échos.",
    "",
    "Vous avez rétabli l’ordre",
    "sur Kepler‑442.",
    "Les factions reconsidéreront",
    "leurs ambitions.",
    "Les Sentinelles ont achevé",
    "leurs observations.",
    "Les Juggernauts Dorés demeurent en sommeil",
    "dans l’obscurité.",
    "",
    "Mais quelque chose subsiste.",
    "",
    "À la lisière du champ d’astéroïdes,",
    "au‑delà de la portée des capteurs",
    "conventionnels, quelque chose d’ancien s’agite.",
    "",
    "Les concepteurs originels du DESTINY",
    "vous observent.",
    "Ils sont satisfaits de ce que",
    "vous êtes devenu.",
    "",
    "Ils attendent.",
    "",
    "Ils se préparent.",
    "",
    "Ils seront prêts.",
    "",
    "",
    "",
};

#define NUM_VICTORY_LINES_FR (sizeof(VICTORY_SCROLL_LINES) / sizeof(VICTORY_SCROLL_LINES_FR[0]))

static const char *VICTORY_SCROLL_RU[] = {
    "",
    "",
    "",
    "ИНЦИДЕНТ НА КЕПЛЕР‑442:",
    "ЗАВЕРШЁН",
    "",
    "Астероиды… они",
    "никогда не были по‑настоящему хаотичными.",
    "",
    "Когда вы очищаете последние",
    "волны поля,",
    "истина кристаллизуется",
    "в обломках",
    "тысячи кораблей.",
    "Это была не",
    "добывающая операция.",
    "Это было горнило. Испытание.",
    "",
    "Три фракции отправили",
    "своих лучших.",
    "Красные боевые корабли",
    "Галактического Оборонного Коллектива.",
    "Мирные патрули",
    "Альянса Независимого Сектора.",
    "Корпоративные дроны",
    "Астероидного Добывающего Коллектива.",
    "",
    "Вы уничтожили их всех.",
    "",
    "Фиолетовые Стражи…",
    "они наблюдали.",
    "Наблюдали. Вычисляли…",
    "Ждали.",
    "Когда последний Джаггернаут пал",
    "от вашего огня,",
    "они просто… ушли.",
    "",
    "Будто удовлетворённые.",
    "",
    "Древние системы DESTINY",
    "гудят от цели.",
    "Оружие, которое не должно существовать.",
    "Щиты, бросающие вызов физике.",
    "Корабль неизвестного происхождения,",
    "возрождённый как добывающий,",
    "теперь стоит победителем",
    "в поле пепла и тишины.",
    "",
    "Кто вы на самом деле?",
    "Чем был DESTINY прежде?",
    "",
    "Пустота не даёт ответов.",
    "Только эхо.",
    "",
    "Вы восстановили порядок",
    "на Кеплер‑442.",
    "Фракции пересмотрят",
    "свои амбиции.",
    "Стражи завершили",
    "свои наблюдения.",
    "Золотые Джаггернауты безмолвствуют",
    "во тьме.",
    "",
    "Но кое‑что остаётся.",
    "",
    "На краю поля астероидов,",
    "за пределами досягаемости",
    "обычных сенсоров, что‑то древнее шевелится.",
    "",
    "Создатели DESTINY",
    "наблюдают за вами.",
    "Они довольны тем,",
    "кем вы стали.",
    "",
    "Они ждут.",
    "",
    "Они готовятся.",
    "",
    "Они будут готовы.",
    "",
    "",
    "",
};

#define NUM_VICTORY_LINES_RU (sizeof(VICTORY_SCROLL_LINES) / sizeof(VICTORY_SCROLL_LINES_RU[0]))


// ============================================================================
