// ============================================================================
// OPENING CRAWL TEXT - PROPER LINE BY LINE
// ============================================================================

static const char *OPENING_CRAWL_LINES[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "In the not so distant future in a galaxy",
    "not so far away",
    "",
    "",
    "The Kepler-442 Asteroid Field, once a",
    "treasure trove of minerals, now lies",
    "in ruin.",
    "Asteroids fracture, comets drift", 
    "factions clash.",
    "",
    "Red warships hunt without mercy.",
    "Blue patrols guard with fragile", 
    "honor.",
    "Green drones strip-mine with ruthless ",
    "speed.",
    "And now... the PURPLE SENTINELS",
    "arrive—enigmatic guardians with",
    "unknown intent.",
    "",
    "You fly the DESTINY--",
    "an ancient warship of unknown origin,",
    "reborn as a mining vessel,",
    "armed with rapid-fire cannons,",
    "advanced thrusters, drone missles,",
    "and omnidirectional fire.",
    "",
    "It is fragile, yet fierce.",
    "It carries no banner, no allegiance,",
    "only the will to survive.",
    "",
    "But survival is not enough.",
    "Beyond the factions loom colossal",
    "threats:",
    "MEGA BOSS SHIPS, engines of",
    "annihilation,",
    "whose presence darkens the field",
    "itself.",
    "",
    "And deeper still, from the void,",
    "alien forces gather—",
    "a tide that consumes all in its path.",
    "",
    "Your mission: endure the chaos,",
    "outwit rival factions,",
    "and face the horrors that await.",
    "",
    "The asteroid field is no longer a mine.",
    "It is a crucible of war.",
    "",
    "Survive. Score. Ascend.",
    "",
    "",
};

#define NUM_CRAWL_LINES (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES[0]))

static const char *OPENING_CRAWL_ES[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "En un futuro no tan distante, en una galaxia",
    "no tan lejana",
    "",
    "",
    "El Campo de Asteroides Kepler-442, antes un",
    "tesoro de minerales, ahora yace",
    "en ruinas.",
    "Los asteroides se fracturan, los cometas vagan,",
    "las facciones chocan.",
    "",
    "Los acorazados rojos cazan sin piedad.",
    "Las patrullas azules vigilan con frágil",
    "honor.",
    "Los drones verdes extraen sin descanso,",
    "con velocidad implacable.",
    "Y ahora... los CENTINELAS PÚRPURA",
    "llegan—guardianes enigmáticos con",
    "intenciones desconocidas.",
    "",
    "Pilotas la DESTINY--",
    "una antigua nave de guerra de origen desconocido,",
    "renacida como nave minera,",
    "armada con cañones de disparo rápido,",
    "propulsores avanzados, misiles dron,",
    "y fuego omnidireccional.",
    "",
    "Es frágil, pero feroz.",
    "No porta bandera ni lealtad,",
    "solo la voluntad de sobrevivir.",
    "",
    "Pero sobrevivir no basta.",
    "Más allá de las facciones se alzan",
    "amenazas colosales:",
    "NAVES MEGA JEFE, motores de",
    "aniquilación,",
    "cuya presencia oscurece el campo",
    "mismo.",
    "",
    "Y más profundo aún, desde el vacío,",
    "fuerzas alienígenas se reúnen—",
    "una marea que consume todo a su paso.",
    "",
    "Tu misión: soportar el caos,",
    "burlar a las facciones rivales,",
    "y enfrentar los horrores que te esperan.",
    "",
    "El campo de asteroides ya no es una mina.",
    "Es un crisol de guerra.",
    "",
    "Sobrevive. Puntúa. Asciende.",
    "",
    "",
};

#define NUM_CRAWL_LINES_ES (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES_ES[0]))

static const char *OPENING_CRAWL_FR[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "Dans un futur pas si lointain, dans une galaxie",
    "pas si éloignée",
    "",
    "",
    "Le Champ d’Astéroïdes Kepler-442, autrefois",
    "un trésor de minéraux, gît désormais",
    "en ruines.",
    "Les astéroïdes se fracturent, les comètes dérivent,",
    "les factions s’affrontent.",
    "",
    "Les vaisseaux de guerre rouges chassent sans pitié.",
    "Les patrouilles bleues veillent avec un",
    "honneur fragile.",
    "Les drones verts exploitent sans relâche,",
    "avec une vitesse impitoyable.",
    "Et maintenant… les SENTINELLES VIOLETTES",
    "arrivent — des gardiens énigmatiques aux",
    "intentions inconnues.",
    "",
    "Vous pilotez le DESTINY--",
    "un ancien vaisseau de guerre d’origine inconnue,",
    "renaît comme navire minier,",
    "armé de canons à tir rapide,",
    "de propulseurs avancés, de missiles‑drones,",
    "et d’un tir omnidirectionnel.",
    "",
    "Il est fragile, mais féroce.",
    "Il ne porte ni bannière ni allégeance,",
    "seulement la volonté de survivre.",
    "",
    "Mais survivre ne suffit pas.",
    "Au‑delà des factions se dressent des",
    "menaces colossales :",
    "des MÉGA VAISSEAUX‑BOSSES, moteurs",
    "d’annihilation,",
    "dont la présence assombrit le champ",
    "lui‑même.",
    "",
    "Et plus loin encore, depuis le vide,",
    "des forces extraterrestres se rassemblent —",
    "une marée qui dévore tout sur son passage.",
    "",
    "Votre mission : endurer le chaos,",
    "déjouer les factions rivales,",
    "et affronter les horreurs qui vous attendent.",
    "",
    "Le champ d’astéroïdes n’est plus une mine.",
    "C’est un creuset de guerre.",
    "",
    "Survivez. Marquez. Élevez‑vous.",
    "",
    "",
};

#define NUM_CRAWL_LINES_FR (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES_FR[0]))

static const char *OPENING_CRAWL_RU[] = {
    "",
    "",
    "COMET BUSTER",
    "",
    "В недалёком будущем, в галактике",
    "не такой уж далёкой",
    "",
    "",
    "Поле астероидов Кеплер‑442, некогда",
    "кладезь минералов, теперь лежит",
    "в руинах.",
    "Астероиды трескаются, кометы блуждают,",
    "фракции сталкиваются.",
    "",
    "Красные боевые корабли охотятся без пощады.",
    "Синие патрули стережёт хрупкая",
    "честь.",
    "Зелёные дроны выкачивают ресурсы",
    "с беспощадной скоростью.",
    "И теперь… ФИОЛЕТОВЫЕ СЕНТИНЕЛЫ",
    "прибывают — загадочные стражи с",
    "неизвестными намерениями.",
    "",
    "Вы пилотируете DESTINY--",
    "древний боевой корабль неизвестного происхождения,",
    "возрождённый как добывающий корабль,",
    "оснащённый скорострельными пушками,",
    "усовершенствованными двигателями, ракетами‑дронами",
    "и всенаправленным огнём.",
    "",
    "Он хрупок, но свиреп.",
    "Он не несёт ни знамени, ни верности,",
    "только волю выжить.",
    "",
    "Но выживания недостаточно.",
    "За пределами фракций нависают",
    "колоссальные угрозы:",
    "МЕГА‑КОРАБЛИ БОССОВ — машины",
    "уничтожения,",
    "чьё присутствие омрачает само",
    "поле.",
    "",
    "И глубже, из пустоты,",
    "собираются инопланетные силы —",
    "волна, поглощающая всё на своём пути.",
    "",
    "Ваша миссия: выдержать хаос,",
    "перехитрить соперничающие фракции",
    "и встретить ужасы, что ждут впереди.",
    "",
    "Поле астероидов больше не шахта.",
    "Это горнило войны.",
    "",
    "Выживи. Заработай. Вознесись.",
    "",
    "",
};

#define NUM_CRAWL_LINES_RU (sizeof(OPENING_CRAWL_LINES) / sizeof(OPENING_CRAWL_LINES_RU[0]))

// ============================================================================
// VICTORY SCROLL TEXT - FINALE WHEN WAVE 30 IS BEATEN
// ============================================================================

static const char *VICTORY_SCROLL_LINES[] = {
    "",
    "",
    "",
    "THE KEPLER-442 INCIDENT:",
    "CONCLUDED",
    "",
    "The asteroids... they", 
    "were never truly chaotic.",
    "",
    "As you clear the final",
    "waves from the field,",
    "the truth crystallizes",
    "in the wreckage of a",
    "thousand ships.",
    "This was not a",
    "mining operation.",
    "It was a crucible. A test.",
    "",
    "The three factions sent ",
    "their finest.",
    "The Red Warships of the",
    "Galactic Defense Collective.",
    "The peaceful patrols of the",
    "Independent Sector Alliance.",
    "The corporate drones of ",
    "the Asteroid Mining Collective.",
    "",
    "You destroyed them all.",
    "",
    "The Purple Sentinels...",
    "they were watching.",
    "Observing. Calculating ...",
    "Waiting.",
    "When the final Juggernaut fell",
    "to your fire,",
    "they simply... departed.",
    "",
    "As if satisfied.",
    "",
    "The DESTINY's ancient systems",
    "hum with purpose.",
    "Weapons that should not exist.",
    "Shields that defy physics.",
    "A ship of unknown origin,",
    "reborn as a mining vessel,",
    "now standing victorious",
    "in a field of ash and silence.",
    "",
    "What are you, truly?",
    "What was the DESTINY, before?",
    "",
    "The void offers no answers.",
    "Only echoes.",
    "",
    "You have restored order",
    "to Kepler-442.",
    "The factions will reconsider",
    "their ambitions.",
    "The Sentinels have completed",
    "their observations.",
    "The Golden Juggernauts lie dormant",
    "in the dark.",
    "",
    "But something remains.",
    "",
    "At the edge of the asteroid field,",
    "beyond the reach of conventional",
    "sensors, something ancient stirs.",
    "",
    "The DESTINY's original designers ",
    "are watching.",
    "They are pleased with what you ",
    "have become.",
    "",
    "They are waiting.",
    "",
    "They are preparing.",
    "",
    "They will be ready.",
    "",
    "",
    "",
};

#define NUM_VICTORY_LINES (sizeof(VICTORY_SCROLL_LINES) / sizeof(VICTORY_SCROLL_LINES[0]))

// ============================================================================
