#include <GL/glew.h>
#include <GL/gl.h>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <vector>
#include <ft2build.h>
#include FT_FREETYPE_H
#include "cometbuster.h"
#include "visualization.h"
#include "cometbuster_splashscreen.h"
#include "comet_lang.h"
#include "cometbuster_render_gl.h"
// Include the base64-encoded TTF font header
#include "Monospace.h"  // Generated by ttf_to_base64_header.py

// FreeType font system globals
FT_Library ft_library = NULL;
FT_Face ft_face = NULL;
FT_Face ft_face_cjk = NULL;
unsigned char *ft_font_buffer = NULL;

static inline bool is_cjk(unsigned int cp)
{
    return (
        (cp >= 0x4E00 && cp <= 0x9FFF)   ||  // CJK Unified Ideographs
        (cp >= 0x3400 && cp <= 0x4DBF)   ||  // Extension A
        (cp >= 0xF900 && cp <= 0xFAFF)   ||  // Compatibility Ideographs
        (cp >= 0x20000 && cp <= 0x2EBEF) ||  // Extensions B–F
        (cp >= 0x3000 && cp <= 0x303F)   ||  // CJK punctuation
        (cp >= 0xFF00 && cp <= 0xFFEF)      // Fullwidth forms
    );
}


// ============================================================================
// TEXT RENDERING - Dynamic TTF Rendering with FreeType and Base64 Font
// ============================================================================

#if defined(_WIN32)
    #include <io.h>
    #define access _access
    #define R_OK 4
#else
    #include <unistd.h>
    #include <fcntl.h>
#endif


static const char* CJK_FONT_PATHS[] = {
    // Linux (Fedora / RHEL / CentOS)
    "/usr/share/fonts/google-noto-sans-cjk-fonts/NotoSansCJK-Regular.ttc",

    // Linux (Ubuntu / Debian / Arch)
    "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",

    // Windows
    "C:\\Windows\\Fonts\\msyh.ttc",      // Microsoft YaHei
    "C:\\Windows\\Fonts\\msyhbd.ttc",    // YaHei Bold
    "C:\\Windows\\Fonts\\SimSun.ttc",    // Legacy fallback

    NULL
};

void ft_try_load_cjk_font(void)
{
    if (!ft_library) {
        SDL_Log("[Comet Busters] [FONT] ERROR: FreeType not initialized before CJK load");
        return;
    }

    for (int i = 0; CJK_FONT_PATHS[i] != NULL; i++) {
        const char* path = CJK_FONT_PATHS[i];

        if (access(path, R_OK) == 0) {
            SDL_Log("[Comet Busters] [FONT] Loading CJK font: %s", path);

            FT_Error err = FT_New_Face(ft_library, path, 0, &ft_face_cjk);
            if (!err) {
                SDL_Log("[Comet Busters] [FONT] CJK font loaded successfully");
                return;
            } else {
                SDL_Log("[Comet Busters] [FONT] Failed to load CJK font (%d)", err);
            }
        }
    }

    SDL_Log("[Comet Busters] [FONT] WARNING: No CJK font found on system");
}


void ft_init(void) {
    ft_init_from_base64();
    ft_try_load_cjk_font();
}

// Initialize FreeType library and load base64-encoded TTF font
void ft_init_from_base64(void) {
    if (ft_library) {
        SDL_Log("[Comet Busters] [FONT] FreeType already initialized\n");
        return;
    }
    
    // Initialize FreeType library
    FT_Error error = FT_Init_FreeType(&ft_library);
    if (error) {
        SDL_Log("[Comet Busters] [FONT] ERROR: Failed to initialize FreeType: %d\n", error);
        return;
    }
    
    SDL_Log("[Comet Busters] [FONT] FreeType initialized\n");
    
    // Decode base64 font data
    SDL_Log("[Comet Busters] [FONT] Decoding base64 TTF font data (%zu bytes)...\n", MONOSPACE_FONT_B64_SIZE);
    
    // Use the base64_decode function from Monospace.h
    size_t decoded_size = 0;
    int decode_result = base64_decode(MONOSPACE_FONT_B64, MONOSPACE_FONT_B64_SIZE, &ft_font_buffer, &decoded_size);
    
    if (decode_result != 0 || !ft_font_buffer) {
        SDL_Log("[Comet Busters] [FONT] ERROR: Failed to decode base64 font data\n");
        FT_Done_FreeType(ft_library);
        ft_library = NULL;
        return;
    }
    
    SDL_Log("[Comet Busters] [FONT] Base64 decoded: %zu bytes -> %zu bytes\n", MONOSPACE_FONT_B64_SIZE, decoded_size);
    
    // Load the font face from memory
    error = FT_New_Memory_Face(ft_library, ft_font_buffer, (FT_Long)decoded_size, 0, &ft_face);
    if (error) {
        SDL_Log("[Comet Busters] [FONT] ERROR: Failed to load TTF face: %d\n", error);
        free(ft_font_buffer);
        ft_font_buffer = NULL;
        FT_Done_FreeType(ft_library);
        ft_library = NULL;
        return;
    }
    
    SDL_Log("[Comet Busters] [FONT] TTF font loaded successfully\n");
    SDL_Log("[Comet Busters] [FONT] Font family: %s, style: %s\n", ft_face->family_name, ft_face->style_name);
}

// Cleanup FreeType resources
void ft_cleanup(void) {
    if (ft_face) {
        FT_Done_Face(ft_face);
        ft_face = NULL;
    }
    if (ft_face_cjk) {
        FT_Done_Face(ft_face_cjk);
        ft_face = NULL;
    }
    if (ft_library) {
        FT_Done_FreeType(ft_library);
        ft_library = NULL;
    }
    if (ft_font_buffer) {
        free(ft_font_buffer);
        ft_font_buffer = NULL;
    }
}

// UTF-8 Decoder: Convert UTF-8 byte sequence to Unicode codepoint
// Returns the Unicode codepoint and updates bytes_read with number of bytes consumed
// Handles:
//   - ASCII (1 byte): 0x00-0x7F
//   - Latin Extended (2 bytes): 0xC0-0xDF
//   - Cyrillic, CJK, etc. (3 bytes): 0xE0-0xEF
//   - Full Unicode (4 bytes): 0xF0-0xF7
unsigned int utf8_to_codepoint(const unsigned char *str, int *bytes_read) {
    if (!str || !bytes_read) {
        *bytes_read = 0;
        return 0;
    }
    
    unsigned char c0 = str[0];
    
    // Single byte (ASCII: 0x00-0x7F)
    if (c0 < 0x80) {
        *bytes_read = 1;
        return c0;
    }
    
    // Two bytes (Latin Extended: 0xC0-0xDF)
    // Examples: á (0xE1), é (0xE9), ñ (0xF1)
    if ((c0 & 0xE0) == 0xC0) {
        *bytes_read = 2;
        unsigned char c1 = str[1];
        if ((c1 & 0xC0) != 0x80) {
            return 0;  // Invalid UTF-8
        }
        return ((c0 & 0x1F) << 6) | (c1 & 0x3F);
    }
    
    // Three bytes (Cyrillic, Greek, etc: 0xE0-0xEF)
    // Examples: А (0x0410), Б (0x0411), etc.
    if ((c0 & 0xF0) == 0xE0) {
        *bytes_read = 3;
        unsigned char c1 = str[1];
        unsigned char c2 = str[2];
        if ((c1 & 0xC0) != 0x80 || (c2 & 0xC0) != 0x80) {
            return 0;  // Invalid UTF-8
        }
        return ((c0 & 0x0F) << 12) | ((c1 & 0x3F) << 6) | (c2 & 0x3F);
    }
    
    // Four bytes (CJK, Emoji: 0xF0-0xF7)
    if ((c0 & 0xF8) == 0xF0) {
        *bytes_read = 4;
        unsigned char c1 = str[1];
        unsigned char c2 = str[2];
        unsigned char c3 = str[3];
        if ((c1 & 0xC0) != 0x80 || (c2 & 0xC0) != 0x80 || (c3 & 0xC0) != 0x80) {
            return 0;  // Invalid UTF-8
        }
        return ((c0 & 0x07) << 18) | ((c1 & 0x3F) << 12) | ((c2 & 0x3F) << 6) | (c3 & 0x3F);
    }
    
    // Invalid UTF-8 sequence
    *bytes_read = 1;
    return 0;
}

// Calculate actual text width based on FreeType glyph metrics
float gl_calculate_text_width(const char *text, int font_size) {

    if (!text || !text[0] || !ft_face) return 0.0f;
    
    // Set font size (in 1/64th of a point, so multiply by 64)
    FT_Error error = FT_Set_Pixel_Sizes(ft_face, 0, font_size);
    if (error) {
        SDL_Log("[Comet Busters] [FONT] Warning: Failed to set font size\n");
        return 0.0f;
    }
    
    float width = 0.0f;
    
    // Process UTF-8 text
    for (int i = 0; text[i]; ) {
        int bytes_read = 0;
        unsigned int codepoint = utf8_to_codepoint((const unsigned char*)&text[i], &bytes_read);
        
        if (bytes_read == 0) {
            i++;
            continue;
        }
        
        // Load the glyph and get metrics
        FT_UInt glyph_index = FT_Get_Char_Index(ft_face, codepoint);
        error = FT_Load_Glyph(ft_face, glyph_index, FT_LOAD_DEFAULT);
        
        if (!error) {
            // Use advance width from the glyph slot
            width += (float)(ft_face->glyph->advance.x >> 6);  // Convert from 1/64th pixel to pixels
        }
        
        i += bytes_read;
    }
    
    return width;
}

void gl_draw_text_simple(const char *text, int x, int y, int font_size) {
    if (!text || !text[0] || !ft_face) return;
    
    // Set font size
    FT_Error error = FT_Set_Pixel_Sizes(ft_face, 0, font_size);
    if (error) {
        SDL_Log("[Comet Busters] [FONT] Warning: Failed to set font size\n");
        return;
    }
    
    // Disable scissor test to prevent text clipping
    glDisable(GL_SCISSOR_TEST);
    
    float current_x = (float)x;
    float baseline_y = (float)y;
    float line_height = (float)font_size * 1.2f;  // Line height with 20% spacing
    
    // Build vertex array
    static std::vector<Vertex> verts;

    if (verts.empty()) verts.resize(MAX_VERTS);
    int vert_count = 0;
    
    // Process UTF-8 text
    for (int i = 0; text[i] && vert_count < MAX_VERTS - 6; ) {
        int bytes_read = 0;
        unsigned int codepoint = utf8_to_codepoint((const unsigned char*)&text[i], &bytes_read);
        
        if (bytes_read == 0) {
            i++;
            continue;
        }
        
        // Handle newline character
        if (codepoint == '\n') {
            current_x = (float)x;
            baseline_y += line_height;
            i += bytes_read;
            continue;
        }
        
        // Get glyph index and load it
        FT_UInt glyph_index = FT_Get_Char_Index(ft_face, codepoint);
        error = FT_Load_Glyph(ft_face, glyph_index, FT_LOAD_RENDER);
        
        if (error) {
            // Skip glyphs that can't be loaded, but advance position
            if (FT_Load_Glyph(ft_face, glyph_index, FT_LOAD_DEFAULT) == 0) {
                current_x += (float)(ft_face->glyph->advance.x >> 6);
            }
            i += bytes_read;
            continue;
        }
        
        FT_GlyphSlot slot = ft_face->glyph;
        FT_Bitmap *bitmap = &slot->bitmap;
        
        if (bitmap->buffer && bitmap->width > 0 && bitmap->rows > 0) {
            // Render glyph bitmap as vertices
            float glyph_x = current_x + slot->bitmap_left;
            float glyph_y = baseline_y - slot->bitmap_top;
            
            for (int row = 0; row < (int)bitmap->rows && vert_count < MAX_VERTS - 6; row++) {
                float pixel_y = glyph_y + row;
                
                for (int col = 0; col < (int)bitmap->width && vert_count < MAX_VERTS - 6; col++) {
                    unsigned char pixel_value = bitmap->buffer[row * bitmap->pitch + col];
                    
                    if (pixel_value > 3) {
                        float pixel_x = glyph_x + col;
                        float alpha = gl_state.color[3] * ((float)pixel_value / 255.0f);
                        
                        float r = gl_state.color[0];
                        float g = gl_state.color[1];
                        float b = gl_state.color[2];
                        
                        // Create two triangles for the pixel
                        verts[vert_count++] = {pixel_x, pixel_y, r, g, b, alpha};
                        verts[vert_count++] = {pixel_x + 1.0f, pixel_y, r, g, b, alpha};
                        verts[vert_count++] = {pixel_x + 1.0f, pixel_y + 1.0f, r, g, b, alpha};
                        
                        verts[vert_count++] = {pixel_x, pixel_y, r, g, b, alpha};
                        verts[vert_count++] = {pixel_x + 1.0f, pixel_y + 1.0f, r, g, b, alpha};
                        verts[vert_count++] = {pixel_x, pixel_y + 1.0f, r, g, b, alpha};
                    }
                }
            }
        }
        
        // Advance to next character position
        current_x += (float)(slot->advance.x >> 6);
        i += bytes_read;
    }
    
    // Draw all glyphs at once
    if (vert_count > 0) {
        glEnable(GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        draw_vertices(verts.data(), vert_count, GL_TRIANGLES);
    }
}

